spring:
  application:
    name: user-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: user-service
  cloud:
    bus:
      refresh:
        enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/netflix?useUnicode=true&characterEncoding=utf8&useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=UTC
    password: 123456
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8081

mybatis:
  type-aliases-package: com.gupaoedu.example.userserviceprovider.mapper.entitys
management:
  endpoints:
    web:
      exposure:
        include: refresh
hystrix:
  command:
    default:  #全局配置， feignclient#method(param)
      execution:
        timeout:
          enable: true
        isolation:
          thread:
            timeoutInMilliseconds: 1000