spring:
  application:
    name: user-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: user-service
  cloud:
    bus:
      refresh:
        enabled: true
server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: refresh