spring:
  application:
    name: goods-service
  datasource:
    url: jdbc:mysql://localhost:3306/netflix?useUnicode=true&characterEncoding=utf8&useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=UTC
    password: 123456
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8083
mybatis:
  type-aliases-package: com.laven.goodsserviceprovider.mapper.entitys

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka

