spring:
  application:
    name: order-service
  cloud:
    bus:
      enabled: true
  kafka:
    bootstrap-servers: localhost:90902
    consumer:
      group-id: order-service
server:
  port: 8082
management:
  endpoints:
    web:
      exposure:
        include: refresh