spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lavenwl/Config-Server.git
          username: lavenwl@gmail.com
          password: hogjik-bemtux-wUzxe2
    bus:
      enabled: true
      trace:
        enabled: true
      refresh:
        enabled: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: config-server
server:
  port: 9091
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
